[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter. (this setup was made for 1 user utilisation)
[default_session]
command = "/usr/local/bin/wrappedhl"
user = "[username]" # Here, the greeter is supposed to be your main account, it will launch Hyprland and swaylock

# /!\ USE GREETD ONLY IF YOU KNOW WHAT YOU'RE DOING, you can easily get stuck in a "boot" loop !
# file in /etc/greetd
