
# █▀ ▀█▀ ▄▀█ █▀█ █▀ █░█ █ █▀█
# ▄█ ░█░ █▀█ █▀▄ ▄█ █▀█ █ █▀▀

palette = "catppuccin_mocha"

format = '''
[┌─](lavender)\[ $hostname$username\]─\( $directory\) $git_branch$git_metrics$git_status$git_state$python$c$ocaml$cmd_duration 
[└─](lavender) $character''' 

[character]

[cmd_duration]
format = 'took [$duration]($style) '

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
read_only = ' '
truncation_length = 4

[git_branch]
format = 'on [$symbol $branch(:$remote_branch)]($style) '
symbol = ''

[git_state]

[python]
symbol = ' '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[c]

[ocaml]
symbol = '  '

[git_metrics]
disabled = false
format = '\([+$added]($added_style) [-$deleted]($deleted_style)\) '

[git_status]
format = '[\[$all_status$ahead_behind\]]($style) '

[username]
show_always = true
style_user = 'bold blue'
format = '[$user]($style) '

[hostname]
ssh_only = false
ssh_symbol = '󰌘 '
format = '[$ssh_symbol$hostname]($style) as '
style = 'bold green'



[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
